"""empty message

Revision ID: 36e2d6b6388f
Revises: 
Create Date: 2021-03-13 14:08:57.687241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36e2d6b6388f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sectors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sectors_name'), 'sectors', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('initial_investment_amt', sa.Float(), nullable=False),
    sa.Column('dollars_available', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_name'), 'portfolios', ['name'], unique=True)
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_symbol', sa.String(length=32), nullable=True),
    sa.Column('legal_name', sa.String(length=128), nullable=True),
    sa.Column('current_share_price', sa.Float(), nullable=True),
    sa.Column('total_number_shares', sa.Float(), nullable=True),
    sa.Column('shares_avail', sa.Float(), nullable=True),
    sa.Column('initial_offering_price', sa.Float(), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_legal_name'), 'stocks', ['legal_name'], unique=True)
    op.create_index(op.f('ix_stocks_ticker_symbol'), 'stocks', ['ticker_symbol'], unique=True)
    op.create_table('mutual_funds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('initial_investment_amt', sa.Float(), nullable=False),
    sa.Column('nav', sa.Float(), nullable=True),
    sa.Column('shares_outstanding', sa.Float(), nullable=True),
    sa.Column('dollars_available', sa.Float(), nullable=True),
    sa.Column('dollars_invested', sa.Float(), nullable=True),
    sa.Column('total_mf_sector', sa.Float(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.Column('sids', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['sids'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mutual_funds_name'), 'mutual_funds', ['name'], unique=True)
    op.create_table('current_fund_price',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mf_id', sa.Integer(), nullable=False),
    sa.Column('stocks_id', sa.Integer(), nullable=False),
    sa.Column('total_shares', sa.Float(), nullable=True),
    sa.Column('price_per_share', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['mf_id'], ['mutual_funds.id'], ),
    sa.ForeignKeyConstraint(['stocks_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id', 'mf_id', 'stocks_id')
    )
    op.create_table('holdings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('port_id_hold', sa.Integer(), nullable=False),
    sa.Column('mf_id_hold', sa.Integer(), nullable=False),
    sa.Column('mf_shares', sa.Float(), nullable=True),
    sa.Column('mf_nav', sa.Float(), nullable=True),
    sa.Column('port_amount_invested', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['mf_id_hold'], ['mutual_funds.id'], ),
    sa.ForeignKeyConstraint(['port_id_hold'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id', 'port_id_hold', 'mf_id_hold')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('holdings')
    op.drop_table('current_fund_price')
    op.drop_index(op.f('ix_mutual_funds_name'), table_name='mutual_funds')
    op.drop_table('mutual_funds')
    op.drop_index(op.f('ix_stocks_ticker_symbol'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_legal_name'), table_name='stocks')
    op.drop_table('stocks')
    op.drop_index(op.f('ix_portfolios_name'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_sectors_name'), table_name='sectors')
    op.drop_table('sectors')
    # ### end Alembic commands ###
